use UNIVER;

/* задание 1*/
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPE
			from AUDITORIUM_TYPE Inner Join AUDITORIUM
			on AUDITORIUM_TYPE.AUDITORIUM_TYPE=AUDITORIUM.AUDITORIUM_TYPE;

/* задание 2*/
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
			from AUDITORIUM_TYPE INNER JOIN AUDITORIUM
			on AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE AND
			AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';

/* задание 3*/
select STUDENT.NAME,  FACULTY.FACULTY, SUBJECT.SUBJECT_NAME, PULPIT.PULPIT, PROFESSION.PROFESSION_NAME,
	CASE
	when(PROGRESS.NOTE = 6) then 'шесть'
	when(PROGRESS.NOTE = 7) then 'семь'
	when(PROGRESS.NOTE = 8) then 'восемь'
	end [PROGRESS.NOTE]
from PROGRESS
inner join STUDENT on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join SUBJECT on SUBJECT.SUBJECT = PROGRESS.SUBJECT
inner join GROUPS on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join PULPIT on PULPIT.PULPIT=SUBJECT.PULPIT
inner join FACULTY on FACULTY.FACULTY = PULPIT.FACULTY
where PROGRESS.NOTE between 6 and 8
--asc в порядке возрастания
--desc в порядке убывания
order by PROGRESS.NOTE desc, FACULTY.FACULTY asc, PULPIT.PULPIT asc, PROFESSION.PROFESSION asc, STUDENT.NAME asc

/*задание 4*/
select isnull (TEACHER.TEACHER_NAME, '***')[Преподаватель],
PULPIT.PULPIT [Кафедра]
from PULPIT left outer join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT;

/*задание 5*/
--1
select PULPIT.FACULTY, PULPIT.PULPIT, PULPIT.PULPIT_NAME
from PULPIT full outer join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT
where TEACHER.TEACHER is null

--2
select TEACHER.TEACHER_NAME, TEACHER.TEACHER, TEACHER.PULPIT, TEACHER.GENDER
from PULPIT full outer join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT
where TEACHER.TEACHER is not null

--3
select * from TEACHER full outer join PULPIT
on PULPIT.PULPIT = TEACHER.PULPIT

/*задание 6*/
select AUDITORIUM_TYPE.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM
from AUDITORIUM_TYPE cross join AUDITORIUM
where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE

